apiVersion: v1
kind: PersistentVolumeClaim
meta
  name: postgres-pvc
  namespace: nodejs-app
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard  # Minikube utilise "standard" par défaut