name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and analyze
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Ensures full history for better analysis

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'  # Specify a Node.js version

      - name: Install ESLint and security plugin
        run: |
          npm install --save-dev eslint eslint-plugin-security
          npx eslint --init  # Initialize ESLint with default config if not present
        working-directory: .

      - name: Run ESLint SAST Scan
        run: |
          npx eslint . --ext .js,.jsx --format json --output-file eslint-report.json
        working-directory: .
        continue-on-error: true  # Continue even if ESLint finds issues

      - name: Run Jest with Coverage
        run: |
          npx jest --coverage --coverageReporters=lcov --coverageDirectory=coverage
        working-directory: .
        continue-on-error: true  # Continue even if tests fail

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v5.2.0
        with:
          projectBaseDir: .
          args: >
            -Dsonar.projectKey=JS_App
            -Dsonar.eslint.reportPaths=eslint-report.json     
            -X
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

#  -Dsonar.coverageReportPaths=coverage/lcov.info