name: Deploy Node.js to Proxmox

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Debug - List files in workspace
      run: ls -la

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm install

    - name: Build project
      run: npm run build

    - name: Deploy to Proxmox
      run: |
        ssh -o StrictHostKeyChecking=no user@10.90.122.235 "
          mkdir -p /path/to/deploy &&
          rm -rf /path/to/deploy/* &&
          tar -czf - . | ssh user@10.90.122.235 'tar -xzf - -C /path/to/deploy'
        "
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
