name: Deploy Node.js app to Proxmox

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Deploy to Proxmox server
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: "10.90.122.235"
          username: "etienne"
          key: ${{ secrets.PROXMOX_SSH_PRIVATE_KEY }}
          port: 22
          script: |
            set -e

            echo "🔹 Vérification du répertoire de déploiement..."
            cd /home/etienne || exit 1

            if [ ! -d "nodeJs-Auth-Crud" ]; then
              git clone https://github.com/THISmann/nodeJs-Auth-Crud.git
            fi

            cd nodeJs-Auth-Crud || exit 1
            git checkout main
            git pull origin main

            echo "🔹 Vérification de Docker..."
            if ! systemctl is-active --quiet docker; then
              sudo systemctl start docker
            fi

            echo "🔹 Vérification de Docker Compose..."
            if ! command -v docker-compose &> /dev/null; then
              sudo apt update && sudo apt install -y docker-compose
            fi

            echo "🔹 Lancement de l'application..."
            docker-compose down
            docker-compose build
            docker-compose up -d

            echo "✅ Déploiement réussi !"
